Repository InnerSourceCommons/InnerSourceLearningPath, pull requests merged in 2020-04, with the labels that each got.

#241 german translation of chapter 01 ready for review
  trusted-committer/de/01-introduction.asciidoc
Labels: Article, Translation, Trusted Committer

#242 Create outline-oreilly.md
  outline-oreilly.md
Labels: Meta, Video, Workbook

#236 Chinese Version on Introduction
  introduction/zh/01-介绍.asciidoc
  introduction/zh/02-InnerSource解决的问题.asciidoc
  introduction/zh/03-InnerSource如何运作.asciidoc
  introduction/zh/04-InnerSource的收益.asciidoc
  introduction/zh/05-InnerSource的原则.asciidoc
  introduction/zh/06-结论.asciidoc
  introduction/zh/提纲.asciidoc
Labels: Article, Translation
