Repository InnerSourceCommons/InnerSourceLearningPath, pull requests merged in 2021-04, with the labels that each got.

#390 Fix new site links
  config/urls.yaml
  contributor/01-introduction-article.asciidoc
  contributor/04-mechanics-of-contributing-article.asciidoc
  contributor/de/01-introduction-article-de.asciidoc
  contributor/it/01-introduction-article-it.asciidoc
  contributor/it/04-mechanics-of-contributing-article-it.asciidoc
  contributor/ja/01-introduction-article-ja.asciidoc
  contributor/ja/04-mechanics-of-contributing-article-ja.asciidoc
  contributor/outline.asciidoc
  contributor/video-proposal.asciidoc
  contributor/zh/01-introduction-zh.asciidoc
  contributor/zh/04-mechanics-of-contributing-zh.asciidoc
  introduction/03-how-works.asciidoc
  introduction/04-benefits.asciidoc
  introduction/05-principles.asciidoc
  introduction/06-conclusion.asciidoc
  introduction/de/03-how-works-de.asciidoc
  introduction/de/04-benefits-de.asciidoc
  introduction/de/05-principles-de.asciidoc
  introduction/de/06-conclusion-de.asciidoc
  introduction/it/03-how-works.asciidoc
  introduction/it/04-benefits.asciidoc
  introduction/it/05-principles.asciidoc
  introduction/it/06-conclusion.asciidoc
  introduction/ja/03-how-works-ja.asciidoc
  introduction/ja/04-benefits-ja.asciidoc
  introduction/ja/05-principles-ja.asciidoc
  introduction/ja/06-conclusion-ja.asciidoc
  introduction/ru/03-how-works.asciidoc
  introduction/ru/06-conclusion.asciidoc
  introduction/zh/03-how-works-zh.asciidoc
  introduction/zh/06-conclusion-zh.asciidoc
  product-owner/01-opening-article.asciidoc
  product-owner/03-major-benefits-are-built-into-the-innersource-process-article.asciidoc
  product-owner/04-new-roles-and-responsibilities-article.asciidoc
  product-owner/05-recap-takeaways-article.asciidoc
  trusted-committer/01-introduction.asciidoc
  trusted-committer/02-ensuring-product-quality.asciidoc
  trusted-committer/03-keeping-the-community-healthy.asciidoc
  trusted-committer/04-uplevelling-community-members.asciidoc
  trusted-committer/05-lowering-the-barriers-to-entry.asciidoc
  trusted-committer/06-advocating-for-the-communitys-needs.asciidoc
  trusted-committer/07-becoming-a-trusted-committer.asciidoc
  trusted-committer/de/01-introduction-de.asciidoc
  trusted-committer/de/02-ensuring-product-quality-de.asciidoc
  trusted-committer/de/03-keeping-the-community-healthy-de.asciidoc
  trusted-committer/de/04-uplevelling-community-members.asciidoc
  trusted-committer/de/05-lowering-the-barriers-to-entry.asciidoc
  trusted-committer/de/06-advocating-for-the-communitys-needs.asciidoc
  trusted-committer/de/07-becoming-a-trusted-committer.asciidoc
  trusted-committer/ja/01-introduction-ja.asciidoc
  trusted-committer/ja/02-ensuring-product-quality-ja.asciidoc
  trusted-committer/ja/03-keeping-the-community-healthy-ja.asciidoc
  trusted-committer/zh/01-introduction-zh.asciidoc
  trusted-committer/zh/02-ensuring-product-quality-zh.asciidoc
  trusted-committer/zh/04-uplevelling-community-members-zh.asciidoc
Labels: Self-Hosting

#384 #254 german translation contributor chapter 02
  contributor/de/02-becoming-a-contributor-article-de.asciidoc
Labels: Contributor, Translation

#392 Add index.md Japanese translations
  contributor/ja/index.md
  introduction/ja/index.md
  product-owner/ja/index.md
  trusted-committer/ja/index.md
Labels: Self-Hosting, Translation

#387 #254 german translation contributor chapter 03
  contributor/de/03-contributor-ethos-article-de.asciidoc
Labels: Contributor, Translation

#391 Clean up scripts for old website
  scripts/README.md
  scripts/generate_hugo_learning_path_markdown.js
  scripts/generate_jekyll_learning_path_markdown.js
  scripts/generate_learning_path_markdown.js
Labels: Self-Hosting
