Repository InnerSourceCommons/InnerSourceLearningPath, pull requests merged in 2022-01, with the labels that each got.

#458 Add machine translation instructions
  CONTRIBUTING.md
Labels: Translation

#448 Translate 02-becoming-a-contributor-article.asciid
  contributor/es/02-becoming-a-contributor-article-es.asciidoc
Labels: Contributor, Article, Translation

#464 New index.md file for the workbook
  workbook/index.md
Labels: Self-Hosting
